from models.area_conocimiento import Area_conocimiento 
from models.institucion import  Institucion
from models.modulo import Modulo
from models.rol import Rol
from models.permiso import Permiso
from models.usuario import Usuario
from models.etapa import Etapa
from models.fase import Fase
from models.convocatoria import Convocatoria
from models.Programacion_fase import Programacion_fase
from models.postulacion_evaluador import Postulacion_evaluador
from models.modalidad import Modalidad
from models.rubrica import Rubrica
from models.item_rubrica import Item_rubrica
from models.proyecto import Proyecto
from models.autor import Autor
from models.tipo_documento import Tipo_documento
from models.titulo_academico import Titulo_academico
from models.detalle_personal import Detalle_personal
from models.asistente import Asistente
from models.proyecto_convocatoria import Proyecto_convocatoria
from models.participante_proyecto import Participante_proyecto
from models.rubrica_resultados import Rubrica_resultado
from models.sala import Sala 
from models.sala_asignada import Sala_asignada
from models.presentacion_proyecto import Presentacion_proyecto
from models.historial_actividades_admin import historial_actividades_admin