from .area_conocimiento import Area_conocimiento 
from .institucion import  Institucion
from .modulo import Modulo
from .rol import Rol
from .permiso import Permiso
from .usuario import Usuario
from .etapa import Etapa
from .fase import Fase
from .convocatoria import Convocatoria
from .programacion_fase import Programacion_fase
from .postulacion_evaluador import Postulacion_evaluador
from .modalidad import Modalidad
from .rubrica import Rubrica
from .item_rubrica import Item_rubrica
from .proyecto import Proyecto
from .autor import Autor
from .tipo_documento import Tipo_documento
from .titulo_academico import Titulo_academico
from .detalle_institucional import Detalle_institucional
from .asistente import Asistente
from .proyecto_convocatoria import Proyecto_convocatoria
from .participante_proyecto import Participante_proyecto
from .rubrica_resultado import Rubrica_resultado
from .sala import Sala 
from .detalle_sala import Detalle_sala
from .presentacion_proyecto import Presentacion_proyecto
from .historial_actividades_admin import Historial_admin